### ISSUE TITLE
Research on Map API (10)

### ISSUE THREAD

**Issue by YesugenB** [YesugenB/valetbike#1]
~10 hours

**Comment by carolynnguyen614** [comment]
1. Research Google Map API

- How do other companies implement that API?
- How does the API retrieve addresses?
-Can the API calculate distance from a user? 
-What kind of information does the API return? 

2. Record findings and share links in a google doc

**Comment by YesugenB** [comment]
https://developers.google.com/maps/documentation/javascript/overview
