### ISSUE TITLE
Research on Payment micro-service (10)

### ISSUE THREAD

**Issue by YesugenB** [YesugenB/valetbike#2]
~10 hours

**Comment by s-yjunn** [comment]
Questions:

- E-commerce logic
- Different potential ways of payments (Paypal/Venmo/credit cards/...)
- Security
- Implementation difficulties
- Information needed
- etc...

**Comment by oliviademeo** [comment]
https://developer.paypal.com/docs/checkout/integrate/?_ga=2.54001384.1570766970.1635276830-1594752508.1635276830
https://www.paypal.com/buttons/smart?flowloggingId=f90083337271f
https://www.davidangulo.xyz/simple-paypal-checkout-in-ruby-on-rails-using-orders-api-v2/
