### ISSUE TITLE
 Implementations of Ruby & Ruby on Rails (10)

### ISSUE THREAD

**Issue by YesugenB** [YesugenB/valetbike#4]
~10 hours each

**Comment by carolynnguyen614** [comment]
Pre-requisite:
Make sure dev environ is functioning

1. Learn/Research tools in Ruby on Rails
- watch tutorials or do readings that explain the features of Rails
-write down helpful code/programs that might be useful in the project
2. Learn Ruby
- watch tutorials or do readings that explain the logistics of the language
- write down helpful code/programs that might be useful in the project

**Comment by jennyzyt** [comment]
Learn Ruby on rails framework and commands needed to start implementation.
Learn the Ruby language (syntax, symbols)
